-- MySQL Script generated by MySQL Workbench
-- Mon Apr 30 19:59:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hvq
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hvq
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hvq` DEFAULT CHARACTER SET latin1 ;
USE `hvq` ;

-- -----------------------------------------------------
-- Table `hvq`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hvq`.`category` (
  `category_id` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hvq`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hvq`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `active` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hvq`.`expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hvq`.`expense` (
  `expense_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_id` VARCHAR(255) NULL DEFAULT NULL,
  `date` DATE NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` DOUBLE NOT NULL,
  `id_category` VARCHAR(255) NULL DEFAULT NULL,
  `id_user` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`expense_id`),
  INDEX `FK23pkapnoq2ah8pw2uc6y6npr0` (`id_category` ASC),
  INDEX `FKg090f125fduu26v3qhvgd62dq` (`id_user` ASC),
  CONSTRAINT `FK23pkapnoq2ah8pw2uc6y6npr0`
    FOREIGN KEY (`id_category`)
    REFERENCES `hvq`.`category` (`category_id`),
  CONSTRAINT `FKg090f125fduu26v3qhvgd62dq`
    FOREIGN KEY (`id_user`)
    REFERENCES `hvq`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hvq`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hvq`.`role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hvq`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hvq`.`user_role` (
  `user_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  INDEX `FKa68196081fvovjhkek5m97n3y` (`role_id` ASC),
  INDEX `FK859n2jvi8ivhui0rl0esws6o` (`user_id` ASC),
  CONSTRAINT `FK859n2jvi8ivhui0rl0esws6o`
    FOREIGN KEY (`user_id`)
    REFERENCES `hvq`.`user` (`user_id`),
  CONSTRAINT `FKa68196081fvovjhkek5m97n3y`
    FOREIGN KEY (`role_id`)
    REFERENCES `hvq`.`role` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

INSERT INTO `role` (`role_id`, `role`) VALUES
(1, 'ADMIN'),
(2, 'USER');


INSERT INTO `user_role` (`user_id`, `role_id`) VALUES
(1, 2),
(2, 2),
(3, 2);

INSERT INTO `category` (`category_id`,`description`)  VALUES
('Limpieza','Limpieza'),
('Alimentos','Alimentos'),
('Electricidad','Electricidad'),
('Agua','Agua'),
('Gas','Gas'),
('Celular','Celular'),
('Cable','Cable'),
('Internet','Internet'),
('Salidas/Tiempo Libre','Salidas/Tiempo Libre'),
('Gastos Vehiculo','Gastos Vehiculo'),
('Tarjeta de credito','Tarjeta de credito'),
('Deportes','Deportes'),
('Ropa','Ropa'),
('Viajes','Viajes'),
('Higiene','Higiene'),
('Gastos Medicos','Gastos Medicos');







